### ISSUE TITLE
StripGradleApiTask.isGradleApi also matches AGP

### ISSUE THREAD

**Issue by gabrielittner** [GradleUp/gr8#10]
I wanted to add all of `compileOnly` to `classpathConfiguration` to get rid of R8 warnings about missing classes. However that fails with:

```
Could not determine the dependencies of task ':plugin:gr8StripGradleApi'.
> Failed to query the value of task ':plugin:gr8StripGradleApi' property 'gradleApiJar$plugin_common'.
   > Collection contains more than one matching element.
```

When I printed all files in the configurationthe configuration I found this:

```
.../.gradle/caches/modules-2/files-2.1/dev.gradleplugins/gradle-api/8.0.2/81ef2cba43a0896316935ece786174490ea30758/gradle-api-8.0.2.jar
.../.gradle/caches/modules-2/files-2.1/com.android.tools.build/gradle-api/7.4.2/5f81693f719b0472898c69dafb42befbb18de887/gradle-api-7.4.2.jar
```

Not sure if this is possible to avoid just based on the path. Maybe it could be possible to have more than one `classpathConfiguration` and make it configurable which ones are stripped.

**Comment by gabrielittner** [comment]
> Maybe it could be possible to have more than one classpathConfiguration and make it configurable which ones are stripped.

Or instead of strip being a boolean it becomes a configuration name and both `classpathConfiguration` (not stripped) and `strippedClasspathConfiguration` (automatically stripped) are added to the gr8 task.

**Comment by martinbonnin** [comment]
Thanks for reporting this! TBH the whole `strip` thing is a bit of a hack I added to quickly get rid of some R8 errors. But it may hide a bug in R8 or something else,  I'll try to investigate this a bit more. 

> Or instead of strip being a boolean it becomes a configuration name and both classpathConfiguration (not stripped) and strippedClasspathConfiguration (automatically stripped) are added to the gr8 task.

The `StripGradleApi` task has `"org/gradle/internal/impldep/META-INF/"` hardcoded so it doesn't apply to anything else. 

As a first step, I'll tweak the filter to look into the jar file for files in `org/gradle/internal/impldep/META-INF/`, that will match 1:1 the task. And hopefully at some point we can get rid of the hack altogether.

**Comment by gabrielittner** [comment]
Thanks for fixing this

**Comment by martinbonnin** [comment]
Sure thing! Now I'm trying to dig into why this was an issue in the first place and can't find a reproducer anymore. Do you have anything at hand by any chance where `stripGradleApi` is required?

**Comment by gabrielittner** [comment]
I've got a reproducer 
1. Checkout this branch https://github.com/freeletics/mad/compare/gr8-strip-gradle
2. Run `./gradlew testR8Jar`

Fails with the following until enabling `stripGradleApi`
```
> Task :deeplinks-plugin:testR8Jar FAILED
Error in /Users/gabrielittner/.gradle/caches/modules-2/files-2.1/dev.gradleplugins/gradle-api/8.0.2/81ef2cba43a0896316935ece786174490ea30758/gradle-api-8.0.2.jar:org/gradle/internal/impldep/META-INF/versions/9/org/bouncycastle/crypto/digests/MD5Digest.class:
com.gradleup.gr8.relocated.ot: Class content provided for type descriptor org.gradle.internal.impldep.META-INF.versions.9.org.bouncycastle.crypto.digests.MD5Digest actually defines class org.gradle.internal.impldep.org.bouncycastle.crypto.digests.MD5Digest
```

**Comment by gabrielittner** [comment]
With #14 the `test-plugin` also reproduces it

**Comment by martinbonnin** [comment]
Thanks! Took a deeper look and this is related to [multi release jar files](https://www.baeldung.com/java-multi-release-jar) to support multiple versions of Java from the same jar. I'm not sure if R8 supports this but in all cases, files should be inside `META-INF/version` and not `org/gradle/internal/impldep/META-INF/versions` so I'm just going to assume this is a Gradle packaging issue and keep the workaround as is for now.
