### ISSUE TITLE
Relocate without shrinkning

### ISSUE THREAD

**Issue by vlsi** [GradleUp/gr8#5]
Hi,

I want to relocate AWS SDK for https://github.com/burrunan/gradle-s3-build-cache, and it looks like proguard is either "relocate+obfuscate" or "just keep old package names".

What I want is to just relocate packages under `com.github.burrunan.s3cache.relocated` package, and I don't want all the classes to be renamed as `a.class` so the stacktraces are understandable.

Do you know if there's a proguard configuration for that?

It looks like `-keep` would keep the original names (which would defeat the purpose of shading as it would conflict with other dependencies), however, `-flattenpackagehierarchy` and `-repackageclasses` obfuscate the names.

**Comment by martinbonnin** [comment]
You might want to try `-dontshrink`. @hvisser has had some success with that [recently](https://github.com/GradleUp/gr8/issues/4#issuecomment-1204500766).

**Comment by martinbonnin** [comment]
Actually looks like `-dontobfuscate` might be a better bet according to [this SO question](https://stackoverflow.com/questions/51860843/how-to-turn-off-only-the-obfuscation-in-android-r8).

**Comment by vlsi** [comment]
`-dontobfuscate` keeps the original package names, so it does not really help :-/

```
software/amazon/awssdk/...
org/apache/http/..
```

**Comment by martinbonnin** [comment]
Turns out it just landed in R8 main: https://r8.googlesource.com/r8/+/81ae5c8b3ef02120cea8ac15bfc0f71aac66f72f

I'll give it a shot this week end.

**Comment by martinbonnin** [comment]
Turns out this is working since version 0.6 that uses R8 3.4 sorry I forgot to update this issue. To use it use `-dontobfuscate` together with `-repackageclasses`

```
-dontobfuscate
-repackageclasses com.example.relocated
```
